"""
Performance metrics calculation module.
Single source of truth for all backtest and portfolio metric calculations.
Uses Capital Models to separate Fixed vs Compounding logic.
"""
import numpy as np
import pandas as pd
from typing import Dict, Optional, List, Any

# Import the capital models we just created
from .capital_models import BaseCapitalModel


def calculate_tail_ratios(
    returns: pd.Series, 
    lower_p: float = 1.0, 
    upper_p: float = 99.0, 
    inner_lower_p: float = 30.0, 
    inner_upper_p: float = 70.0,
    gaussian_ratio: float = 4.43
) -> Dict[str, float]:
    """Calculate percentile-based tail ratios (fat-tail measure)."""
    demeaned = returns - returns.mean()
    
    p1 = demeaned.quantile(lower_p / 100)
    p30 = demeaned.quantile(inner_lower_p / 100)
    p70 = demeaned.quantile(inner_upper_p / 100)
    p99 = demeaned.quantile(upper_p / 100)
    
    if abs(p30) < 1e-10 or abs(p70) < 1e-10:
        return {"lower_tail": 0.0, "upper_tail": 0.0, "tail_risk": 0.0}
    
    lower_tail = (abs(p1) / abs(p30)) / gaussian_ratio
    upper_tail = (abs(p99) / abs(p70)) / gaussian_ratio
    tail_risk = np.sqrt(lower_tail * upper_tail)
    
    return {
        "lower_tail": round(lower_tail, 3),
        "upper_tail": round(upper_tail, 3),
        "tail_risk": round(tail_risk, 3)
    }


def calculate_average_drawdown(drawdown_series: pd.Series) -> float:
    """
    Calculate average drawdown across all distinct drawdown periods.
    
    Now takes a pre-calculated drawdown series (generated by a Capital Model),
    so it doesn't need to know about initial_capital or fixed/compounding logic.
    """
    in_drawdown = drawdown_series < 0
    period_id = (~in_drawdown).cumsum()
    
    max_drawdowns = drawdown_series[in_drawdown].groupby(period_id[in_drawdown]).min()
    
    return max_drawdowns.mean() * 100 if len(max_drawdowns) > 0 else 0.0


def calculate_metrics(
    equity: pd.Series,
    daily_pnl: pd.Series,
    capital_model: BaseCapitalModel,  # <-- Replaces use_fixed_capital boolean
    initial_capital: float = 100_000.0,
    positions: Optional[pd.Series] = None,
    cumulative_fees: Optional[pd.Series] = None,
    cumulative_turnover: Optional[pd.Series] = None,
    risk_free_rate: float = 0.0,
    trading_days: int = 252
) -> Dict[str, float]:
    """
    Unified metric calculation for both individual strategies and portfolios.
    """
    n_years = len(equity) / trading_days
    
    # ==========================================
    # 1. Core Return & Risk Metrics (Delegated to Capital Model)
    # ==========================================
    returns = capital_model.calculate_returns(equity, daily_pnl, initial_capital)
    total_return = capital_model.calculate_total_return(returns)
    cagr = capital_model.calculate_cagr(total_return, n_years)
    
    vol_pct = returns.std() * np.sqrt(trading_days) * 100
    sharpe_ratio = (cagr - risk_free_rate) / (vol_pct / 100) if vol_pct > 0 else 0.0
    
    # Sortino Ratio
    downside_returns = returns[returns < 0]
    downside_vol = downside_returns.std() * np.sqrt(trading_days) if len(downside_returns) > 0 else 0.0
    sortino_ratio = (cagr - risk_free_rate) / (downside_vol / 100) if downside_vol > 0 else 0.0
    
    # Drawdowns (Delegated to Capital Model)
    drawdown_series = capital_model.calculate_drawdown(equity, initial_capital)
    max_drawdown_pct = drawdown_series.min() * 100
    avg_drawdown_pct = calculate_average_drawdown(drawdown_series)
    
    # Tail Risk & Win Rate
    tail_metrics = calculate_tail_ratios(returns)
    win_rate_pct = (daily_pnl > 0).sum() / len(daily_pnl) * 100 if len(daily_pnl) > 0 else 0.0
    
    # Skew and Kurtosis
    skew_val = float(returns.skew()) if not pd.isna(returns.skew()) else 0.0
    kurtosis_val = float(returns.kurtosis()) if not pd.isna(returns.kurtosis()) else 0.0
    
    metrics = {
        'total_return_pct': total_return * 100,
        'cagr_pct': cagr * 100,
        'annual_volatility_pct': vol_pct,
        'sharpe_ratio': sharpe_ratio,
        'sortino_ratio': sortino_ratio,
        'max_drawdown_pct': max_drawdown_pct,
        'avg_drawdown_pct': avg_drawdown_pct,
        'win_rate_pct': win_rate_pct,
        'skew': skew_val,
        'kurtosis': kurtosis_val,
        **tail_metrics
    }

    # ==========================================
    # 2. Fee & Turnover Metrics (If data provided)
    # ==========================================
    if cumulative_fees is not None and cumulative_turnover is not None:
        daily_fees = cumulative_fees.diff().fillna(0)
        daily_turnover = cumulative_turnover.diff().fillna(0)
        
        raw_pnl = daily_pnl + daily_fees
        net_pnl = daily_pnl.sum()
        gross_pnl = raw_pnl.sum()
        total_fees = daily_fees.sum()
        
        fee_drag_ratio = total_fees / abs(gross_pnl) if gross_pnl != 0 else 0.0
        cost_efficiency = net_pnl / gross_pnl if gross_pnl != 0 else 1.0
        
        gross_return = gross_pnl / initial_capital
        gross_cagr = (1 + gross_return) ** (1 / n_years) - 1 if n_years > 0 else 0.0
        
        equity_prev = equity.shift(1).fillna(initial_capital)
        gross_returns = raw_pnl / equity_prev
        gross_vol = gross_returns.std() * np.sqrt(trading_days)
        gross_sharpe = gross_cagr / gross_vol if gross_vol > 0 else 0.0
        
        net_sharpe = metrics.get('sharpe_ratio', 0.0)
        sharpe_drag = gross_sharpe - net_sharpe
        
        avg_daily_turnover = daily_turnover.mean()
        turnover_penalty = avg_daily_turnover * 0.1
        turnover_adjusted_sharpe = max(0.0, net_sharpe - turnover_penalty)
        
        metrics.update({
            'gross_pnl': gross_pnl,
            'gross_return': gross_return,
            'gross_return_pct': gross_return * 100,
            'net_pnl': net_pnl,
            'total_fees_currency': total_fees,
            'fee_drag_ratio': fee_drag_ratio,
            'cost_efficiency': cost_efficiency,
            'gross_sharpe_ratio': gross_sharpe,
            'sharpe_drag': sharpe_drag,
            'turnover_adjusted_sharpe': turnover_adjusted_sharpe,
            'avg_daily_turnover': avg_daily_turnover,
            'total_turnover': daily_turnover.sum(),
            'total_fee_drag_pct': (total_fees / initial_capital) * 100,
            'annualized_fee_drag_pct': ((total_fees / initial_capital) * 100 / n_years) if n_years > 0 else 0.0
        })
        
    return metrics

def calculate_diversification_metrics(
    individual_returns: pd.DataFrame,
    weights: np.ndarray,
    strategy_names: List[str],
    trading_days: int = 252
) -> Dict[str, Any]:
    """
    Portfolio-specific metrics: Diversification Ratio, Volatility Reduction, 
    and Average Correlation.
    """
    # Calculate individual and portfolio volatility
    ind_vols = individual_returns[strategy_names].std() * np.sqrt(trading_days)
    port_returns = (individual_returns[strategy_names] * weights).sum(axis=1)
    port_vol = port_returns.std() * np.sqrt(trading_days)
    
    weighted_sum_vols = np.sum(weights * ind_vols.values)
    
    div_ratio = weighted_sum_vols / port_vol if port_vol > 0 else 1.0
    vol_reduction = (1 - port_vol / weighted_sum_vols) * 100 if weighted_sum_vols > 0 else 0.0
    
    # Average Correlation (Upper triangle of correlation matrix)
    corr_matrix = individual_returns[strategy_names].corr()
    upper_tri = corr_matrix.where(
        np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
    )
    avg_corr = upper_tri.stack().mean()
    
    return {
        'diversification_ratio': div_ratio,
        'volatility_reduction_pct': vol_reduction,
        'avg_correlation': avg_corr,
        'individual_vols_pct': {name: vol * 100 for name, vol in zip(strategy_names, ind_vols)},
        'portfolio_vol_pct': port_vol * 100
    }